Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Psmb.FlatNav:
            - Main
    Ui:
      resources:
        javascript:
          'Psmb.FlatNav:FlatNav':
            resource: resource://Psmb.FlatNav/Public/JavaScript/FlatNav/Plugin.js
        stylesheets:
          'Psmb.FlatNav:FlatNav':
              resource: resource://Psmb.FlatNav/Public/JavaScript/FlatNav/Plugin.css
      frontendConfiguration:
        Psmb_FlatNav:
          presets:
            tree:
              type: tree
              label: Tree
              icon: tree
            ## Example
            # news:
            #   label: News
            #   icon: newspaper
            #   type: flat
            #   nodeTreeProviderClassName: 'Vendor\Site\NodeTreeProvider' # must implement NodeTreeProviderInterface
            #   parentNodeAggregateId: '<node-id>'
            #   newNodeType: 'Your.Namespace:News'
            #   disablePagination: false

  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Psmb.FlatNav:Backend':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Psmb\FlatNav\Controller\.*'
    mvc:
      routes:
        'Psmb.FlatNav':
          position: 'before Neos.Neos'
